version: '3.8'
services:
    web:
        container_name: go-cart-service
        build:
            context: ./
            target: dev
            dockerfile: ./docker/go/Dockerfile
        ports:
            - 8080:8080
        volumes:
            - .:/go/src/github.com/scastillop/fiber_skeleton
        env_file:
            - ./config/dev.env
